language: node_js
node_js:
    - "6.9.0"
    - "8.5.0"

install:
    - npm install .
    - npm install kelda/deployment-engine-downloader && ./node_modules/.bin/kelda-downloader

before_script:
    - npm install -g gulp-cli

script:
    - gulp lint
    - ./kelda inspect ./redisExample.js graphviz

notifications:
    slack:
        secure: lzLue+cih98Y2NzK8mJNOfuBwlTmneHxRclBytZagHFOEVgv5wdZDI9Fs539f95ZbzJBVoU/snM/SgCAGtAjzKYSatMXnCrQJHGm+LiJnX2Ir31Z63lvQJExj0kZyGBFoDBMapJHfZzyQbwgiBq9tKyllIEEBvLqGrqdueB3QaoznnPzrizKYHS0pPup1uotrki99sr2vn/K6+uSfZyaOdmDHqdifoMzp+qNT52MoahjYFvyZ/OrwpkTyfeUsw+QhtZUJuzWFQe+DmTVJM+m/+b38jf/4kgv7iRbvsFZ6cbdY7tvbpBvcUnPdieWELZMl3QEHigiD5ndOLk/0Lp/YD5EuBbjs70S7QcwsO2pcEpN1ZcDu0uZhXjI9m8AKa8dUJKdajTnhelLnTwyAvCespdPNJO5PTfbXk2xmtAhN12YbFqKkV+I5CQOvA9twx6g0hpBoZhQU53kPId//qQxwNNyudIB0U3JSF9PVRiCur8yK+oGixmNkx5LshwU5ZixnGY9XDgg8lCjCec45qGEFsJZ3jkMaharLSYLpAWdtxYTYKtECuBMn/ebBPbq4lEGdjwMmENICOpwEFvA+tsKVtS6othJh6oFaHgHaKtO+deqJmkyGpztDDOycKxtb65SiC8qCaXFho9oeNrGVD9wSKD++0gjNyUncfotPB9G1R4=
